language: python
python:
    - 2.7
before_install:
    - git clone https://github.com/cscutcher/pelican-plugins.git
install:
    - pip install gitpython ghp-import markdown pelican
script:
    - make github
