language: python
python:
- 2.7
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-git
- openssl aes-256-cbc -K $encrypted_5c59e1ea750c_key -iv $encrypted_5c59e1ea750c_iv
  -in travis_ssh_key.enc -out travis_ssh_key -d
- cp travis_ssh_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git clone https://github.com/cscutcher/pelican-plugins.git
install:
- pip install ghp-import markdown pelican
script:
- PYTHON_PATH="$PYTHON_PATH:/usr/lib/python2.7/dist-packages/" make github
